projects:
  asteriosAPI:
    schemaPath: amplify/backend/api/asteriosAPI/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/api/AWSApi.ts
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
