"use strict";
/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten
exports.__esModule = true;
exports.createServerRaidbossDeathLogs = exports.deleteRaidBoss = exports.updateRaidBoss = exports.createRaidBoss = exports.deleteServer = exports.updateServer = exports.createServer = void 0;
exports.createServer = "\n  mutation CreateServer(\n    $input: CreateServerInput!\n    $condition: ModelServerConditionInput\n  ) {\n    createServer(input: $input, condition: $condition) {\n      id\n      asteriosId\n      name\n      enabled\n      _version\n      _deleted\n      _lastChangedAt\n      createdAt\n      updatedAt\n      bosses {\n        items {\n          id\n          isoDate\n          content\n          contentSnippet\n          link\n          title\n          serverId\n          raidBossId\n          _version\n          _deleted\n          _lastChangedAt\n          createdAt\n          updatedAt\n        }\n        nextToken\n        startedAt\n      }\n    }\n  }\n";
exports.updateServer = "\n  mutation UpdateServer(\n    $input: UpdateServerInput!\n    $condition: ModelServerConditionInput\n  ) {\n    updateServer(input: $input, condition: $condition) {\n      id\n      asteriosId\n      name\n      enabled\n      _version\n      _deleted\n      _lastChangedAt\n      createdAt\n      updatedAt\n      bosses {\n        items {\n          id\n          isoDate\n          content\n          contentSnippet\n          link\n          title\n          serverId\n          raidBossId\n          _version\n          _deleted\n          _lastChangedAt\n          createdAt\n          updatedAt\n        }\n        nextToken\n        startedAt\n      }\n    }\n  }\n";
exports.deleteServer = "\n  mutation DeleteServer(\n    $input: DeleteServerInput!\n    $condition: ModelServerConditionInput\n  ) {\n    deleteServer(input: $input, condition: $condition) {\n      id\n      asteriosId\n      name\n      enabled\n      _version\n      _deleted\n      _lastChangedAt\n      createdAt\n      updatedAt\n      bosses {\n        items {\n          id\n          isoDate\n          content\n          contentSnippet\n          link\n          title\n          serverId\n          raidBossId\n          _version\n          _deleted\n          _lastChangedAt\n          createdAt\n          updatedAt\n        }\n        nextToken\n        startedAt\n      }\n    }\n  }\n";
exports.createRaidBoss = "\n  mutation CreateRaidBoss(\n    $input: CreateRaidBossInput!\n    $condition: ModelRaidBossConditionInput\n  ) {\n    createRaidBoss(input: $input, condition: $condition) {\n      id\n      name\n      floor\n      image\n      chest\n      _version\n      _deleted\n      _lastChangedAt\n      createdAt\n      updatedAt\n      deathLogs {\n        items {\n          id\n          isoDate\n          content\n          contentSnippet\n          link\n          title\n          serverId\n          raidBossId\n          _version\n          _deleted\n          _lastChangedAt\n          createdAt\n          updatedAt\n        }\n        nextToken\n        startedAt\n      }\n    }\n  }\n";
exports.updateRaidBoss = "\n  mutation UpdateRaidBoss(\n    $input: UpdateRaidBossInput!\n    $condition: ModelRaidBossConditionInput\n  ) {\n    updateRaidBoss(input: $input, condition: $condition) {\n      id\n      name\n      floor\n      image\n      chest\n      _version\n      _deleted\n      _lastChangedAt\n      createdAt\n      updatedAt\n      deathLogs {\n        items {\n          id\n          isoDate\n          content\n          contentSnippet\n          link\n          title\n          serverId\n          raidBossId\n          _version\n          _deleted\n          _lastChangedAt\n          createdAt\n          updatedAt\n        }\n        nextToken\n        startedAt\n      }\n    }\n  }\n";
exports.deleteRaidBoss = "\n  mutation DeleteRaidBoss(\n    $input: DeleteRaidBossInput!\n    $condition: ModelRaidBossConditionInput\n  ) {\n    deleteRaidBoss(input: $input, condition: $condition) {\n      id\n      name\n      floor\n      image\n      chest\n      _version\n      _deleted\n      _lastChangedAt\n      createdAt\n      updatedAt\n      deathLogs {\n        items {\n          id\n          isoDate\n          content\n          contentSnippet\n          link\n          title\n          serverId\n          raidBossId\n          _version\n          _deleted\n          _lastChangedAt\n          createdAt\n          updatedAt\n        }\n        nextToken\n        startedAt\n      }\n    }\n  }\n";
exports.createServerRaidbossDeathLogs = "\n  mutation CreateServerRaidbossDeathLogs(\n    $input: CreateServerRaidbossDeathLogsInput!\n    $condition: ModelServerRaidbossDeathLogsConditionInput\n  ) {\n    createServerRaidbossDeathLogs(input: $input, condition: $condition) {\n      id\n      isoDate\n      content\n      contentSnippet\n      link\n      title\n      serverId\n      raidBossId\n      _version\n      _deleted\n      _lastChangedAt\n      createdAt\n      updatedAt\n      server {\n        id\n        asteriosId\n        name\n        enabled\n        _version\n        _deleted\n        _lastChangedAt\n        createdAt\n        updatedAt\n        bosses {\n          nextToken\n          startedAt\n        }\n      }\n      raidBoss {\n        id\n        name\n        floor\n        image\n        chest\n        _version\n        _deleted\n        _lastChangedAt\n        createdAt\n        updatedAt\n        deathLogs {\n          nextToken\n          startedAt\n        }\n      }\n    }\n  }\n";
